### ISSUE TITLE
dinamic topic

### ISSUE THREAD

**Issue by elanvelazquez** [nik-zp/Vue-Mqtt-Example#1]
Hi Nik-zp, i need some help here. Im trying to set a topic dinamically. I have a dashboard so when I select some item on a select HTML tag i need to catch this value and suscribe to this topic also, put this value on the line down here. How can I do this? 

Thank you a lot.

https://github.com/nik-zp/Vue-Mqtt-Example/blob/2278198ae30746fe5e86171705323d0a4b69f682/src/components/Sub1.vue#L15

Sorry about my english.

**Comment by nik-zp** [comment]
Hi. I think that you can subscribe to the template. (v2.0.1)
```
    'template/+' (data, topic) {
      if (topic.split('/').pop() === '12345') {
        console.log('topic:', 'template/12345')
      }
    }
```

**Comment by elanvelazquez** [comment]
Hi, i solve the issue with this method

`this.$mqtt.on('message', (topic, message) => {
if (topic.match('param/param/param/')) {
console.log('matched!')
}
})`

i put this code on mounted and thats how i solved this.

Thank You so much
